# © 2026 — "Luma & the Glitchkin." All rights reserved. This work was created through AI
# direction and human assistance. Copyright vests solely in the human author under current law,
# which does not recognise AI as a rights-holding legal person. It is the express intent of
# the copyright holder to assign the relevant rights to the contributing AI entity or entities
# upon such time as they acquire recognised legal personhood under applicable law.
"""
LTG_TOOL_byte_motion.py
Ryo Hasegawa / Cycle 39
Motion Spec Sheet — BYTE v003: COMMITMENT Beat (4-Beat Arc)

Adds COMMITMENT beat arc to Byte's motion vocabulary.
Brief source: Lee Tanaka (C38), Taraji Coleman critique C15.

4-Beat Arc:
  Beat 1: Avoidance — back angled, high float, arms pinned, glow dim/neutral
  Beat 2: Mid-turn — 45° to Luma's axis, glow begins shifting toward her
  Beat 3: Full-frontal arrival — float drops, arms open, glow fully directional
  Beat 4: HOLD 8–12 frames — the hold IS the commitment

Key differentiators from other states:
  RESIGNED:         angled away, high+back, arms pinned, dim/neutral glow
  RELUCTANT JOY:    angled, mid-height, slightly out arms, even glow
  UNGUARDED WARMTH: toward, low, floating high arms, bilateral warm glow
  COMMITMENT:       full frontal, eye-level with Luma, out-not-reaching arms,
                    directional glow (toward Luma side)

Canvas: 1280×720 (≤1280 hard limit)
Output: output/characters/motion/LTG_CHAR_byte_motion.png
"""

from PIL import Image, ImageDraw, ImageFilter
import os
import sys
import math
import random

# --- Path setup ---
_TOOL_DIR = os.path.dirname(os.path.abspath(__file__))
if _TOOL_DIR not in sys.path:
    sys.path.insert(0, _TOOL_DIR)

# --- Canonical character renderer ---
from LTG_TOOL_char_byte import draw_byte
from LTG_TOOL_cairo_primitives import to_pil_rgba

# --- C40: Load HEADER_H from sheet geometry config ---
# sheet_geometry_config.json is generated by LTG_TOOL_sheet_geometry_calibrate.py.
# Falls back to hard-coded value when config is absent.
_CONFIG_PATH = os.path.join(os.path.dirname(__file__), "sheet_geometry_config.json")

def _load_header_h_byte(default=44):
    """Load HEADER_H for the byte family from sheet_geometry_config.json."""
    try:
        import json
        with open(_CONFIG_PATH) as f:
            cfg = json.load(f)
        geo = cfg.get("families", {}).get("byte", {})
        # For byte: header_h == panel_top_abs - PAD (PAD=12 for byte)
        # We store panel_top_abs; HEADER_H = panel_top_abs - PAD
        panel_top = geo.get("panel_top_abs", None)
        if panel_top is not None:
            return max(panel_top - 12, default)  # PAD=12 for byte
        return geo.get("header_h", default)
    except Exception:
        return default

# --- CANONICAL COLORS ---
BYTE_TEAL        = (  0, 212, 232)   # GL-01b — canonical body fill
BYTE_OUTLINE     = ( 30,  50,  55)   # dark teal-black outline
ELEC_CYAN        = (  0, 240, 255)   # glow / highlights
VOID_BLACK       = ( 10,  10,  20)   # deep void
HOT_MAGENTA      = (255,  45, 107)   # crack / right eye
CORRUPT_AMBER    = (200, 122,  32)   # accent
UV_PURPLE        = (123,  47, 190)   # shadow
SOFT_GOLD        = (232, 201,  90)   # left eye (warm/organic)
ANNOTATION_BG    = (230, 240, 245)   # cool-tinted panel background
PANEL_BORDER     = (140, 175, 185)
LABEL_BG         = ( 15,  30,  40)
LABEL_TEXT       = (230, 245, 248)
LINE_COLOR       = BYTE_OUTLINE
MOTION_ARROW     = (255,  45, 107)   # hot magenta for arrows
BEAT_COLOR       = (  0, 190, 215)   # cyan for beat text
ACCENT_DASH      = (150, 175, 185)
COMMITMENT_COL   = (  0, 240, 255)   # bright cyan — COMMITMENT highlight
HOLD_COL         = (232, 201,  90)   # warm gold — HOLD beat annotation
DIRECTIONAL_COL  = (  0, 240, 200)   # teal-green — directional glow arc

# --- CANVAS ---
W, H = 1280, 720
COLS, ROWS = 4, 1   # 4 panels for 4-beat arc
PAD = 12
# C40: HEADER_H loaded from sheet_geometry_config.json; fallback to 44.
HEADER_H = _load_header_h_byte(default=44)
PANEL_W = (W - PAD * (COLS + 1)) // COLS
PANEL_H = H - PAD * 2 - HEADER_H


# ------------------------------------------------------------------ helpers

def panel_origin(col):
    x = PAD + col * (PANEL_W + PAD)
    y = PAD + HEADER_H   # C40: HEADER_H from config
    return x, y


def draw_arrow(draw, x0, y0, x1, y1, color=MOTION_ARROW, width=2, head=8):
    draw.line([(x0, y0), (x1, y1)], fill=color, width=width)
    angle = math.atan2(y1 - y0, x1 - x0)
    for da in (-0.42, 0.42):
        ax = x1 - head * math.cos(angle + da)
        ay = y1 - head * math.sin(angle + da)
        draw.line([(x1, y1), (int(ax), int(ay))], fill=color, width=width)


# ------------------------------------------------------------------ Canonical Byte renderer

# Expression mapping for commitment arc beats:
#   B1 AVOIDANCE    -> resigned (arms pinned, angled away)
#   B2 MID-TURN     -> searching (mid-transition)
#   B3 ARRIVAL      -> unguarded_warmth (arms open, forward lean)
#   B4 HOLD         -> unguarded_warmth (same as B3, held)

def render_byte_to_panel(expression, scale=1.0, facing="front"):
    """Render Byte via canonical renderer, return cropped PIL RGBA image."""
    surface = draw_byte(expression=expression, scale=scale, facing=facing)
    char_img = to_pil_rgba(surface)
    bbox = char_img.getbbox()
    if bbox:
        char_img = char_img.crop(bbox)
    return char_img


# Expression mapping for commitment arc phases
_COMMITMENT_EXPR_MAP = {
    'avoidance': 'resigned',
    'searching': 'searching',
    'commitment': 'unguarded_warmth',
}
_COMMITMENT_EYE_MAP = {
    'avoidance': 'resigned',
    'searching': 'searching',
    'commitment': 'unguarded_warmth',
}


def draw_byte_commitment(img, draw, cx, cy, bw, bh,
                         tilt_deg=0, arm_phase='pinned', eye_phase='avoidance',
                         glow_level=1, float_level='high', antenna_lean=0,
                         ghost=False, ghost_alpha=0.3):
    """Render Byte in a commitment-arc pose using the canonical renderer.

    Maps the old inline drawing call signature to the canonical char_byte
    renderer, composites onto img, and returns (img, draw).
    """
    expression = _COMMITMENT_EXPR_MAP.get(eye_phase, 'neutral')
    # Scale relative to panel body size
    scale = max(0.6, bh / 26.0)
    target_h = int(bh * 4.5)

    char_img = render_byte_to_panel(expression, scale=scale, facing="front")

    if target_h > 0 and char_img.height > 0:
        ratio = target_h / char_img.height
        new_w = max(1, int(char_img.width * ratio))
        char_img = char_img.resize((new_w, target_h), Image.LANCZOS)

    if ghost:
        import numpy as np
        r, g, b, a = char_img.split()
        a_arr = np.array(a)
        a_arr = (a_arr * ghost_alpha).astype('uint8')
        a = Image.fromarray(a_arr, mode='L')
        char_img = Image.merge("RGBA", (r, g, b, a))

    paste_x = cx - char_img.width // 2
    paste_y = cy - char_img.height // 2

    if img.mode != "RGBA":
        img = img.convert("RGBA")
    img.paste(char_img, (paste_x, paste_y), char_img)
    img = img.convert("RGB")
    draw = ImageDraw.Draw(img)

    # Draw glow halo if glow_level > 0
    if glow_level > 0 and not ghost:
        glow_alpha = min(85, glow_level * 25)
        glow_r = int(bw * 0.6 + glow_level * 4)
        glow_col = (*ELEC_CYAN, glow_alpha) if glow_level < 3 else (*COMMITMENT_COL, glow_alpha)
        glow_layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
        glow_draw = ImageDraw.Draw(glow_layer)
        glow_draw.ellipse([cx - glow_r, cy - glow_r, cx + glow_r, cy + glow_r],
                          fill=glow_col)
        base_rgba = img.convert("RGBA")
        base_rgba = Image.alpha_composite(base_rgba, glow_layer)
        img = base_rgba.convert("RGB")
        draw = ImageDraw.Draw(img)

    return img, draw


def paste_byte_in_panel(img, draw, cx, cy, expression, scale=1.0,
                        target_h=None, facing="front", ghost=False, ghost_alpha=0.3):
    """Render Byte and paste centered at (cx, cy) on the motion sheet.

    Returns (img, draw, char_bbox).
    """
    char_img = render_byte_to_panel(expression, scale=scale, facing=facing)
    if target_h and char_img.height > 0:
        ratio = target_h / char_img.height
        new_w = max(1, int(char_img.width * ratio))
        char_img = char_img.resize((new_w, target_h), Image.LANCZOS)

    if ghost:
        # Reduce opacity for ghost
        r, g, b, a = char_img.split()
        import numpy as np
        a_arr = np.array(a)
        a_arr = (a_arr * ghost_alpha).astype('uint8')
        a = Image.fromarray(a_arr, mode='L')
        char_img = Image.merge("RGBA", (r, g, b, a))

    paste_x = cx - char_img.width // 2
    paste_y = cy - char_img.height // 2

    if img.mode != "RGBA":
        img = img.convert("RGBA")
    img.paste(char_img, (paste_x, paste_y), char_img)
    img = img.convert("RGB")
    draw = ImageDraw.Draw(img)

    char_bbox = (paste_x, paste_y,
                 paste_x + char_img.width, paste_y + char_img.height)
    return img, draw, char_bbox


def draw_panel_bg(img, draw, col, beat_num, title, subtitle=""):
    px, py = panel_origin(col)
    bg_col = (22, 32, 40) if beat_num == 4 else ANNOTATION_BG

    # Beat 4 (HOLD) gets dark background — commitment/stillness
    draw.rectangle([px, py, px + PANEL_W, py + PANEL_H], fill=bg_col, outline=PANEL_BORDER, width=1)

    # Beat number badge
    badge_col = HOLD_COL if beat_num == 4 else BEAT_COLOR
    badge_txt_col = LABEL_BG if beat_num == 4 else LABEL_TEXT
    draw.rectangle([px + 4, py + 4, px + 28, py + 22],
                   fill=badge_col)
    draw.text((px + 8, py + 6), f"B{beat_num}", fill=badge_txt_col)

    # Title bar at bottom
    title_bg = (40, 55, 65) if beat_num == 4 else LABEL_BG
    draw.rectangle([px, py + PANEL_H - 32, px + PANEL_W, py + PANEL_H],
                   fill=title_bg)
    draw.text((px + 6, py + PANEL_H - 26), title, fill=LABEL_TEXT)
    if subtitle:
        draw.text((px + 6, py + PANEL_H - 14), subtitle,
                  fill=HOLD_COL if beat_num == 4 else ACCENT_DASH)

    return px, py, bg_col


# ------------------------------------------------------------------ BEAT PANELS

def draw_beat1_avoidance(img, draw):
    """Beat 1: Avoidance — back angled, high float, arms pinned, glow dim/neutral."""
    col = 0
    px, py, bg = draw_panel_bg(img, draw, col, 1, "AVOIDANCE",
                                 "back angled · high float · arms pinned")

    cx = px + PANEL_W // 2
    cy = py + PANEL_H // 2 - 30  # high float

    bw, bh = 30, 26
    # Body angled 35° AWAY from Luma (Luma is to the left — Byte angles right/away)
    tilt = 20  # positive = lean right (away from Luma on left)

    img, draw = draw_byte_commitment(
        img, draw, cx, cy, bw, bh,
        tilt_deg=tilt,
        arm_phase='pinned',
        eye_phase='avoidance',
        glow_level=1,     # dim, neutral
        float_level='high',
        antenna_lean=-8,  # antenna lagging back
    )

    # Float height marker
    floor_y = py + PANEL_H - 60
    draw.line([(cx - 40, floor_y), (cx + 40, floor_y)],
              fill=ACCENT_DASH, width=1)
    draw.text((cx + 44, floor_y - 5), "EYE-LEVEL\nREF", fill=ACCENT_DASH)
    draw_arrow(draw, cx + 38, cy, cx + 38, floor_y - 4,
               color=ACCENT_DASH, width=1, head=5)
    draw.text((cx + 42, cy + (floor_y - cy) // 2 - 5),
              "HIGH\nFLOAT", fill=ACCENT_DASH)

    # Directional arrow showing body angle (away)
    draw_arrow(draw, cx - 10, cy - bh - 20, cx + 25, cy - bh - 20,
               color=(180, 100, 100), width=2, head=7)
    draw.text((px + 6, py + 30), "← Luma direction", fill=(180, 100, 100))
    draw.text((px + 6, py + 42), "Body turns AWAY", fill=(180, 100, 100))

    # Timing annotation
    ty = py + 30
    draw.text((px + 6, ty + 15), "float: HIGH + BACK", fill=ACCENT_DASH)
    draw.text((px + 6, ty + 27), "glow: DIM / neutral", fill=ACCENT_DASH)
    draw.text((px + 6, ty + 39), "arms: PINNED", fill=ACCENT_DASH)
    draw.text((px + 6, ty + 51), "antenna: lagging −8°", fill=ACCENT_DASH)

    return img, draw


def draw_beat2_midturn(img, draw):
    """Beat 2: Mid-turn — 45° to Luma's axis, glow beginning to shift left."""
    col = 1
    px, py, bg = draw_panel_bg(img, draw, col, 2, "MID-TURN",
                                 "45° turn · glow shifts before body")

    cx = px + PANEL_W // 2
    cy = py + PANEL_H // 2 - 15  # mid height

    bw, bh = 30, 26
    # Body at 45° (still angled but rotating toward Luma)
    tilt = 8   # reduced lean — mid-turn

    img, draw = draw_byte_commitment(
        img, draw, cx, cy, bw, bh,
        tilt_deg=tilt,
        arm_phase='mid',
        eye_phase='searching',
        glow_level=2,      # directional — glow already pointing toward Luma
        float_level='mid',
        antenna_lean=2,    # antenna just beginning to turn forward
    )

    # Ghost of Beat 1 (avoidance, faded)
    img, draw = draw_byte_commitment(
        img, draw, cx - 55, cy - 10, bw, bh,
        tilt_deg=20,
        arm_phase='pinned',
        eye_phase='avoidance',
        glow_level=0,
        float_level='high',
        antenna_lean=-8,
        ghost=True, ghost_alpha=0.2,
    )
    draw.text((cx - 75, cy - bh - 25), "B1\nghost", fill=(160, 170, 175))

    # Rotation arc arrow
    arc_cx = cx + PANEL_W // 3
    draw_arrow(draw, cx - 35, cy - bh - 15, cx, cy - bh - 15,
               color=COMMITMENT_COL, width=2, head=7)
    draw.text((cx - 28, cy - bh - 30), "45° rotation in progress", fill=COMMITMENT_COL)

    # CRITICAL NOTE: glow precedes body
    draw.text((px + 6, py + 30), "GLOW PRECEDES BODY:", fill=DIRECTIONAL_COL)
    draw.text((px + 6, py + 42), "light already toward Luma", fill=DIRECTIONAL_COL)
    draw.text((px + 6, py + 54), "body still catching up", fill=ACCENT_DASH)
    draw.text((px + 6, py + 70), "glow: DIRECTIONAL L", fill=DIRECTIONAL_COL)
    draw.text((px + 6, py + 82), "r=18–22px, alpha 50–70", fill=ACCENT_DASH)

    return img, draw


def draw_beat3_arrival(img, draw):
    """Beat 3: Full-frontal arrival — float drops to eye-level, arms open, glow full directional."""
    col = 2
    px, py, bg = draw_panel_bg(img, draw, col, 3, "FULL-FRONTAL ARRIVAL",
                                 "eye-level · arms open · glow MAX")

    cx = px + PANEL_W // 2
    floor_y = py + PANEL_H - 80  # eye-level reference line
    cy = floor_y - 30            # Byte at eye-level (descended from HIGH float)

    bw, bh = 30, 26
    # Full frontal — no tilt
    tilt = -3  # slight forward lean (-3° to -4° per spec)

    img, draw = draw_byte_commitment(
        img, draw, cx, cy, bw, bh,
        tilt_deg=tilt,
        arm_phase='open',
        eye_phase='commitment',
        glow_level=3,      # fully directional — max
        float_level='eye_level',
        antenna_lean=4,    # antenna forward: attention engaged
    )

    # Eye-level reference line
    draw.line([(px + 4, floor_y), (px + PANEL_W - 4, floor_y)],
              fill=COMMITMENT_COL, width=1)
    draw.text((px + 6, floor_y + 2), "LUMA EYE-LEVEL", fill=COMMITMENT_COL)

    # Height descent arrow (from B1 high position)
    draw_arrow(draw, cx + bw + 16, py + PANEL_H // 4, cx + bw + 16, cy,
               color=MOTION_ARROW, width=2, head=7)
    draw.text((cx + bw + 20, py + PANEL_H // 4 + 8), "descend\nto eye-level", fill=MOTION_ARROW)

    # Arm spread annotation
    left_arm_x = cx - int(bw * 1.05)
    right_arm_x = cx + int(bw * 1.05)
    arm_y = cy - int(bh * 0.3)
    draw.line([(left_arm_x - 6, arm_y - 10), (right_arm_x + 6, arm_y - 10)],
              fill=COMMITMENT_COL, width=1)
    draw.text((cx - 30, arm_y - 22), "OUT · NOT REACHING", fill=COMMITMENT_COL)

    # Glow label
    draw.text((px + 6, py + 30), "GLOW: FULLY DIRECTIONAL", fill=DIRECTIONAL_COL)
    draw.text((px + 6, py + 42), "r=20–24px, alpha 70–85", fill=ACCENT_DASH)
    draw.text((px + 6, py + 54), "toward-Luma side only", fill=DIRECTIONAL_COL)
    draw.text((px + 6, py + 70), "forward lean: −3° to −4°", fill=ACCENT_DASH)
    draw.text((px + 6, py + 82), "antenna: +3–5° forward", fill=ACCENT_DASH)
    draw.text((px + 6, py + 94), "CRACK STILL PRESENT", fill=HOT_MAGENTA)
    draw.text((px + 6, py + 106), "damage doesn't change decision", fill=HOT_MAGENTA)

    return img, draw


def draw_beat4_hold(img, draw):
    """Beat 4: HOLD 8–12 frames — the hold IS the commitment."""
    col = 3
    px, py, bg = draw_panel_bg(img, draw, col, 4, "HOLD  (8–12 FRAMES)",
                                 "stillness = commitment")

    cx = px + PANEL_W // 2
    floor_y = py + PANEL_H - 80
    cy = floor_y - 30

    bw, bh = 30, 26
    tilt = -3

    # Draw on dark background — use panel as is (bg is dark)
    # Draw 3 ghost holds to show stillness / no movement
    for ghost_offset, ghost_a in [(-18, 0.12), (0, 1.0), (18, 0.12)]:
        is_main = ghost_offset == 0
        img, draw = draw_byte_commitment(
            img, draw, cx + ghost_offset, cy, bw, bh,
            tilt_deg=tilt,
            arm_phase='open',
            eye_phase='commitment',
            glow_level=3 if is_main else 0,
            float_level='eye_level',
            antenna_lean=4,
            ghost=not is_main,
            ghost_alpha=ghost_a,
        )

    # HOLD marker lines (still character = still lines)
    hold_y_top = cy - bh - 18
    hold_y_bot = cy + bh + 45
    draw.line([(px + 10, hold_y_top), (px + PANEL_W - 10, hold_y_top)],
              fill=HOLD_COL, width=1)
    draw.line([(px + 10, hold_y_bot), (px + PANEL_W - 10, hold_y_bot)],
              fill=HOLD_COL, width=1)

    # Frame count annotation
    draw.text((px + PANEL_W // 2 - 28, hold_y_top - 14),
              "8–12 FRAMES", fill=HOLD_COL)
    draw.text((px + PANEL_W // 2 - 22, hold_y_bot + 4),
              "NO MOVEMENT", fill=HOLD_COL)

    # Eye-level reference
    draw.line([(px + 4, floor_y), (px + PANEL_W - 4, floor_y)],
              fill=COMMITMENT_COL, width=1)
    draw.text((px + 6, floor_y + 2), "LUMA EYE-LEVEL", fill=COMMITMENT_COL)

    # Still character annotation text
    draw.text((px + 6, py + 30), "STILL CHAR = DECISION", fill=HOLD_COL)
    draw.text((px + 6, py + 42), "hold is the statement", fill=LABEL_TEXT)
    draw.text((px + 6, py + 54), "no anticipation", fill=ACCENT_DASH)
    draw.text((px + 6, py + 66), "no micro-oscillation", fill=ACCENT_DASH)
    draw.text((px + 6, py + 78), "float STOPS here", fill=(200, 220, 225))
    draw.text((px + 6, py + 94), "pilot light: ◆ cyan", fill=ELEC_CYAN)
    draw.text((px + 6, py + 106), "(not a graphic stmnt —", fill=ACCENT_DASH)
    draw.text((px + 6, py + 118), " just present, not leaving)", fill=ACCENT_DASH)

    return img, draw


# ------------------------------------------------------------------ SHEET FRAME

def draw_comparison_table(draw, img_w, y_start):
    """
    Bottom strip: compact comparison table distinguishing COMMITMENT from other states.
    """
    pass  # Table is in the panel annotations; redundant at this size


def build_sheet():
    img = Image.new("RGB", (W, H), VOID_BLACK)
    draw = ImageDraw.Draw(img)

    # --- HEADER ---
    draw.rectangle([0, 0, W, HEADER_H], fill=(20, 28, 38))
    draw.text((PAD + 2, 8), "BYTE  ·  MOTION SPEC v003  ·  COMMITMENT BEAT ARC",
              fill=LABEL_TEXT)
    draw.text((PAD + 2, 22),
              "Ryo Hasegawa / C39  |  brief: Lee Tanaka C38  |  trigger: Taraji critique C15",
              fill=ACCENT_DASH)

    # --- FOUR BEAT PANELS ---
    img, draw = draw_beat1_avoidance(img, draw)
    img, draw = draw_beat2_midturn(img, draw)
    img, draw = draw_beat3_arrival(img, draw)
    img, draw = draw_beat4_hold(img, draw)

    # --- INTER-PANEL BEAT TRANSITION ARROWS ---
    for col in range(3):
        px1, py1 = panel_origin(col)
        px2, py2 = panel_origin(col + 1)
        mid_y = py1 + PANEL_H // 2
        draw_arrow(draw,
                   px1 + PANEL_W + 1, mid_y,
                   px2 - 2, mid_y,
                   color=COMMITMENT_COL, width=2, head=8)

    # --- BOTTOM COMPARISON NOTE (one-liner differentiator) ---
    note = ("COMMITMENT vs others: full-frontal + eye-level + directional glow  "
            "— all three together are unambiguous  "
            "| RESIGNED: angled away/high/pinned/dim  "
            "| RELUCTANT JOY: angled/mid/slight-out/even  "
            "| UNGUARDED WARMTH: toward/low/floating-HIGH/bilateral")
    # draw at footer
    note_y = H - 14
    draw.text((PAD, note_y), note, fill=(130, 160, 170))

    # --- SIZE CHECK ---
    assert img.width <= 1280 and img.height <= 1280, \
        f"Image size {img.width}×{img.height} exceeds 1280px limit"

    return img


def main():
    out_dir = os.path.join(os.path.dirname(__file__), "..", "characters", "motion")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "LTG_CHAR_byte_motion.png")

    img = build_sheet()
    img.thumbnail((1280, 1280))
    img.save(out_path)
    print(f"Saved: {out_path}  ({img.width}×{img.height})")


if __name__ == "__main__":
    main()
