#!/usr/bin/env python3
"""
LTG_TOOL_proportion_audit_c37_runner.py
Proportion Audit Runner — Cycle 37
Author: Rin Yamamoto | Cycle 37

Runs the proportion_audit_v002 scan and writes the report to
output/production/proportion_audit_c37.md.

The v002 tool has its report path hardcoded to proportion_audit_c36.md.
This runner monkey-patches the path for the C37 cycle run.

Usage:
    python3 LTG_TOOL_proportion_audit_c37_runner.py
"""

import os
import sys

# Ensure output/tools is on the path so we can import v002
TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, TOOLS_DIR)

import LTG_TOOL_proportion_audit as audit

# Override the report path for C37
PROJECT_ROOT = os.path.dirname(os.path.dirname(TOOLS_DIR))
REPORT_PATH_C37 = os.path.join(PROJECT_ROOT, "output", "production", "proportion_audit_c37.md")

def main():
    results = audit.scan_styleframe_files()

    if not results:
        print("No styleframe generator files found.")
        sys.exit(1)

    audit.print_console_report(results)

    # Build report with C37 heading
    report_md = audit.format_report(results)
    # Update the report heading from C36 to C37
    report_md = report_md.replace("# Proportion Audit — C36", "# Proportion Audit — C37")
    report_md = report_md.replace(
        "*Generated by `LTG_TOOL_proportion_audit.py` — Cycle 36*",
        "*Generated by `LTG_TOOL_proportion_audit_c37_runner.py` (uses v002 engine) — Cycle 37*"
    )

    os.makedirs(os.path.dirname(REPORT_PATH_C37), exist_ok=True)
    with open(REPORT_PATH_C37, 'w', encoding='utf-8') as f:
        f.write(report_md)
    print(f"\nReport written to: {REPORT_PATH_C37}")


if __name__ == "__main__":
    main()
